### ISSUE TITLE
nextToken  : Exception message 

### ISSUE THREAD

**Issue by sanhardik** [concurrencylabs/aws-pricing-tools#6]
At times, the script sends out the following error

Number of logstreams found:[11]
Traceback (most recent call last):
  File "lambda-optimization.py", line 81, in main
    logstreamsargs.pop('nextToken')
KeyError: 'nextToken'
Exception message:[nextToken]

**Comment by concurrencylabs** [comment]
Thanks for bringing this up. We'll look into it and update this thread.

**Comment by concurrencylabs** [comment]
The latest commit contains a fix for this issue. [https://github.com/concurrencylabs/aws-pricing-tools/commit/00b68090080591e7079b9e794366a534e6180e90](url)  Thanks for reporting it.
