### ISSUE TITLE
Error when editing Event Rule

### ISSUE THREAD

**Issue by gjehanin** [concurrencylabs/aws-pricing-tools#8]
Hi,
I would like to modify the rate of 5 min set by default and when I "Update Rule" I get error :

"There was an error while saving rule near-realtime-pricing-cal-ScheduledPricingCalculat-12NVV1P41UU68.
Details: 1 validation error detected: Value 'AWSEvents_near-realtime-pricing-cal-ScheduledPricingCalculat-12NVV1P41UU68_NearRealTimePriceCalculatorFunctionv1' at 'statementId' failed to satisfy constraint: Member must have length less than or equal to 100."

**Comment by concurrencylabs** [comment]
That's a bug in the CloudWatch Events console. A workaround would be to use the CLI instead:

First, find the name of the rule. Get the list of rules:

`aws events list-rules`

From there, get the value for 'Name', corresponding to the rule you want to update.

Update the rule. Let's say you want to change it to 15 minutes:

`aws events put-rule --name <rule-name-from-previous-step> --schedule-expression "rate(15 minutes)" --state ENABLED --description "Invoke Pricing Calculator Lambda function every 15 minutes"`

That should work.

**Comment by Alfaj0r** [comment]
^ thanks for that. Ended here after some googling (totally unrelated to this project), and the workaround totally does work.

**Comment by vishalraut20** [comment]
This was really helping, saved my life. Thanks for the post.

**Comment by kappaj2** [comment]
Still a bug after so long.... disappointing as I'm running into exact same problem.

**Comment by RANJITHRAJKUMAR** [comment]
Oct 4 2019 - Bug is still there and the CLI work around works . Thanks .

**Comment by benzaam** [comment]
the workaround works, thanks! bug is still present though...

**Comment by vikas-gonti** [comment]
How do I edit the configuration to pass the json input to lambda function?

**Comment by AhmedNourJamalElDin** [comment]
Bug is still present

**Comment by huynhr** [comment]
I noticed the ticket is closed, but I am still seeing the same issue.

**Comment by concurrencylabs** [comment]
Yes, the ticket is closed because it's really an issue with the CloudWatch Events console and not the code in this repository. A workaround is to use the CLI (it's described in one of the comments above)

**Comment by katyanigam18** [comment]
Even though the bug still exists, the rule does get updated. You can go back to rule and verify that.

**Comment by PooneetThaper** [comment]
The bug still exists. Unfortunately, unlike the previous commenter, I wasn't able to get things to work that way. I went to the lambda I was trying to add as a target and was able to add the rule as a trigger.
